/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 swat.gltf --transform 
Files: swat.gltf [17.36MB] > /home/dangpham/Desktop/projects/virtual-worlds/threejs_intro/public/models/swat-transformed.glb [1.11MB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/swat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.swatGroup65355.geometry} material={materials.defaultPolygonShader} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/swat-transformed.glb')
